# Generated by Django 4.2.2 on 2023-06-19 12:58

from django.db import migrations, models
import tools


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=tools.random_location, max_digits=7),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=tools.random_location, max_digits=7),
        ),
    ]
