# Generated by Django 4.2.2 on 2023-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=29.25206, max_digits=7),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=65.69562, max_digits=7),
        ),
    ]
